---
- name: Provision GitLab Server
  hosts: gitlab_server
  become: true
  roles:
    - common_tools
    - docker
    - gitlab

- name: Provision CI/CD Core (RKE Co-hosted)
  hosts: rke_tools_server
  become: true
  vars_files:
    - secrets.yml
  roles:
    - java
    - bind9
    - jenkins
    - nexus
    - sonarqube
