---
dns_domain: "abc"
dns_server_ip: "{{ core_tools_ip }}"
dns_records:
  - { name: "jenkins", ip: "{{ core_tools_ip }}" }
  - { name: "nexus", ip: "{{ core_tools_ip }}" }
  - { name: "sonar", ip: "{{ core_tools_ip }}" }
  - { name: "docker", ip: "{{ core_tools_ip }}" }
